//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public double OrderPrice { get; set; }
        public double TaxValue { get; set; }
        public double Discount { get; set; }
        public double Qty { get; set; }
        public int OrderId { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string BatchNo { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
