//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift
    {
        public int ShiftId { get; set; }
        public Nullable<double> OpenBalance { get; set; }
        public double CloseBalance { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public int ShopId { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
    }
}
