//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMenu
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> RecipeId { get; set; }
        public int MenuId { get; set; }
    }
}
