//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Katswiri.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProduct
    {
        public string ProductName { get; set; }
        public string ProductCode { get; set; }
        public int ProductId { get; set; }
        public string CategoryName { get; set; }
        public string BrandName { get; set; }
        public string UnitName { get; set; }
        public string Qty { get; set; }
        public string TaxStatus { get; set; }
        public int CategoryId { get; set; }
        public int BrandId { get; set; }
        public int UnitId { get; set; }
        public Nullable<double> ReOrderLevel { get; set; }
        public string BarCode { get; set; }
        public string Description { get; set; }
    }
}
